export const ALL_PRODUCTS = [
  "Cumin",
  "Coriander",
  "Turmeric",
  "Ginger",
  "Cardamom",
  "Black Pepper",
  "Cinnamon",
  "Clove",
  "Mustard",
  "Fenugreek",
  "Nutmeg",
  "Bay Leaf",
  "Fennel",
  "Star Anise",
  "Asafoetida",
  "Saffron",
  "Curry leaves",
  "Carom seeds (Ajwain)",
  "Black Cumin (Kala Jeera)",
  "Dill seeds",
  "Poppy seeds",
  "Celery Seeds",
  "Bishop's Weed (Radhuni)",
  "Long Pepper (Pippali)",
  "Mace (Javitri)",
  "Tamarind",
  "Turmeric Finger",
  "White Pepper",
  "Red Chilli",
];
