export const ALL_PRODUCTS = [
  {title: "Coriander", navigateTo: "coriander"},
  {title: "Turmeric", navigateTo: "turmeric"},
  {title: "Ginger", navigateTo: "ginger"},
  {title: "Green cardamom", navigateTo: "green-cardamom"},
  {title: "Red Chilli", navigateTo: "chilly"},
  {title: "Cinnamon", navigateTo: "cinnamon"},
  {title: "Black Pepper", navigateTo: "black-pepper"},
  {title: "Clove"},
  {title: "Mustard"},
  {title: "Fenugreek"},
  {title: "Nutmeg"},
  {title: "Bay Leaf"},
  {title: "Fennel"},
  {title: "Star Anise"},
  {title: "Asafoetida"},
  {title: "Saffron"},
  {title: "Curry leaves"},
  {title: "Carom seeds (Ajwain)"},
  {title: "Black Cumin (Kala Jeera)"},
  {title: "Dill seeds"},
  {title: "Poppy seeds"},
  {title: "Celery Seeds"},
  {title: "Bishop's Weed (Radhuni)"},
  {title: "Long Pepper (Pippali)"},
  {title: "Mace (Javitri)"},
  {title: "Tamarind"},
  {title: "Turmeric Finger"},
  {title: "White Pepper"},
];
